= System-Wide Requirements: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt <Thema> spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. [hier ggf. Verweis einfügen]


== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz

- SWFA-1: Das System muss alle Inventar-, Ausleih- und Benutzerdaten persistent speichern. +
Test: Die Datenbank(en) wird/werden mit Testdaten gefüllt. Anschließend wird das System aus­-
geschaltet. Die Daten müssen bei Wiederinbetriebnahme vollständig vorhanden sein.

- SWFA-2: Die Kommunikation zwischen Clients und Server muss verschlüsselt sein. +
Test: Vorhandensein von TLS? Bei einem MitM-Angriff dürfen keine Daten in Klartext lesbar sein.

- SWFA-3: Nach dem Aufrufen der Anwendung müssen sich die Clients/User am Server durch die Eingabe von Benutzernamen und Passwort authentifizieren. +
Test: Werden CSRF-Token verwendet? Sicher gegen Session-Hijacking?

- SWFA-4: Die Daten müssen auf dem Server vor unberechtigten Zugriff geschützt sein. +
Test: Das Ausführen von SQL-Injections darf nicht möglich sein.

- SWFA-5: Die Passwörter zu den Useraccounts müssen serverseitig durch die Verwendung von Hashfunktionen, Salt, Pepper und Stretching sicher gespeichert werden. +
Test: ?


== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)
- NFRU-1: Die Sprache der Benutzeroberfläche ist Deutsch. 
- NFRU-2: Die Startseite soll alle möglichen Aktionen anzeigen, für die der Benutzer die Rechte hat. 
Test: Unterschiedliche Personen (Admin/ normaler Benutzer) werden unterschiedliche Aktionen auf der Startseite angezeigt. 
- NFRU-3: Die Eingaben bei der Suchfunktion werden durch Vorschläge unterstützt. 
Test: Eingabe von nur den ersten 3 Buchstaben eines Gegenstandes in die Suchfunktion. Es wird überprüft, ob der vollständige Name des Gegenstandes angezeigt wird. 
// Frage: ist das zu viel Arbeit? wollen wird so was überhaupt? 
- NFRU-4: Es werden pro Ansicht nur 10 Gegenstände angezeigt. 
// um eine Touchbedienung z.B. auf dem Smartphone zu ermöglichen 
Test: Es werden mindestens 11 Gegenstände im System eingefüht. Es wird überprüft, wie viele Gegenstände auf der Ansicht dargestellt werden. 
- NFRU-5: Ein Gegenstand, der sich im System befindindet, soll mit 5 Klicks oder weniger ausgeliehen oder zurückgegeben werden können. 
Test: Unterschiedliche Gegenstände werden ausgeliehen oder zurückgegeben und die Klicks werden gezählt. 
- NFRU-6: Alle im System befindlichen Daten (Rückgabedatum, Wartungsdatum etc.) sollen in folgendem Format angezeigt werden: DD.MM.JJJJ. 
Test: Es werden einige Anwendungsfällen mit Datumseingabe, durchgeführt. Anschließend wird kontrolliert, ob das System das Datum im richtigen Format gespeichert hat. 


=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

- NFAR-1: Es darf kein falscher Benutzername oder falsches Passwort angegeben werden. 
  Zur Überprüfung wird getestet, ob in diesen Anwendungsfällenin entsprechender Hinweistext angezeigt wird.

- NFAR-2: Ein neuer Benutzername darf kein breits vergeben Namen erhalten.

- NFAR-3: Vollständige Backups werden aller x Tage automatisch erstellt.
Test: Überprüfung auf Inkonsistenz der Daten.

- NFAR-4: Alle Daten müssen in der Datenbank konstistent nach dem ACID-Prinzip gespeichert werden.
Test: Überprüfung auf Inkonsistenz der Daten.

=== Effizienz (Performance)
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

10 User müssen gleichzeitig das System nutzen können.
Test: Mehr Nutzerzugriffe gleichzeitig ausführen.

=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.


== Zusätzliche Anforderungen

=== Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Ressourcenbegrenzungen
* zu nutzende Komponenten / Bibliotheken / Frameworks
* Vorgaben für die Programmiersprache
* zu unterstützende Plattformen / Betriebssysteme
* Physische Begrenzungen für Hardware, auf der das System betrieben werden soll

=== Organisatorische Randbedingungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Anforderungen an Betrieb, Management und Wartung der Anwendung
* zu beachtende Standards, Normen und Regeln

=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Lizensierung der Anwendung
* Datenschutz
* Urheberrechtsschutz
