= System-Wide Requirements: {project-name}
Felix Helmert <felix.helmert@htw-dresden.de>; Silko Grellmann <silko.grellmann@htw-dresden.de>; Dominique Linzmajer <dominique.linzmajer@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt <Thema> spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. 

== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz

- *SWFR-1: Das System muss alle Inventar-, Ausleih- und Benutzerdaten persistent speichern.* +
Test: Die Datenbank(en) wird/werden mit Testdaten gefüllt. Anschließend wird das System aus­-
geschaltet. Die Daten müssen bei Wiederinbetriebnahme vollständig vorhanden sein.

- *SWFR-2: Die Kommunikation zwischen Clients und Server muss verschlüsselt sein.* +
Test: Vorhandensein von (TLS) Bei einem MitM-Angriff dürfen keine Daten in Klartext lesbar sein.

- *SWFR-3: Nach dem Aufrufen der Anwendung müssen sich die Clients/User am Server durch die Eingabe von Benutzernamen und Passwort authentifizieren.* +
Test: Werden Security-Token verwendet, ist dies sicher gegen Session-Hijacking?

- *SWFR-4: Die Daten müssen auf dem Server vor unberechtigten Zugriff geschützt sein.* +
Test: Das Ausführen von SQL-Injections darf nicht möglich sein.

- *SWFR-5: Die Passwörter der Useraccounts müssen sicher und verschlüsselt in der Datenbank gespeichert werden.* +
Test: in der Datenbank nach Passwörtern suchen (sollten nicht in Klartext zu finden sein)


== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)
- *NFRU-1: Die Sprache der Benutzeroberfläche ist Englisch.*
- *NFRU-2: Die Startseite soll alle möglichen Aktionen anzeigen, für die der Benutzer die Rechte hat.* +
Test: Unterschiedliche Personen (Admin/ normaler Benutzer) werden unterschiedliche Aktionen auf der Startseite angezeigt. 
- *NFRU-3: Die Eingaben bei der Suchfunktion werden durch Vorschläge unterstützt.* + 
Test: Eingabe von nur den ersten 3 Buchstaben eines Gegenstandes in die Suchfunktion. Es wird überprüft, ob der vollständige Name des Gegenstandes angezeigt wird. 
// Frage: ist das zu viel Arbeit? wollen wird so was überhaupt? 
- *NFRU-4: Es werden pro Ansicht nur 6 Gegenstände angezeigt.* +
// um eine Touchbedienung z.B. auf dem Smartphone zu ermöglichen 
Test: Es werden mindestens 7 Gegenstände im System eingeführt. Es wird überprüft, wie viele Gegenstände auf der Ansicht dargestellt werden. 
- *NFRU-5: Ein Gegenstand, der sich im System befindet, soll mit 5 Klicks oder weniger ausgeliehen oder zurückgegeben werden können.* + 
Test: Unterschiedliche Gegenstände werden ausgeliehen oder zurückgegeben und die Klicks werden gezählt. 
- *NFRU-6: Alle im System befindlichen Daten (Rückgabedatum, Wartungsdatum etc.) sollen in folgendem Format angezeigt werden: DD.MM.JJJJ.* +
Test: Es werden einige Anwendungsfällen mit Datumseingabe, durchgeführt. Anschließend wird kontrolliert, ob das System das Datum im richtigen Format gespeichert hat. 
- *NFRU-7: Die Gegenstände müssen über einen Barcode gefunden werden können.* + 
Test: Ein Objekt durch scannen eines Barcodes finden.

=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

- *NFRR-1: Es darf kein falscher Benutzername oder falsches Passwort angegeben werden.* +
Test: Zur Überprüfung wird getestet, ob in diesen Anwendungsfällenin entsprechender Hinweistext angezeigt wird.

- *NFRR-2: Ein neuer Benutzername darf keinen bereits vergebenen Namen erhalten.*

- *NFRR-3: Alle Daten müssen in der Datenbank konstistent nach dem ACID-Prinzip gespeichert werden.* +
Test: Überprüfung auf Inkonsistenz der Daten.

- *NFRR-4: Das System sollte eine Verfügbarkeit von 95% gewährleisten.* +
Test: System gezielt zum Absturz bringen, Zeit bis System wieder verfügbar messen

=== Effizienz (Performance)
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

- *NFRP-1: 10 User müssen gleichzeitig das System nutzen können.* +
Test: Mehr Nutzerzugriffe gleichzeitig ausführen.

=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.
- *NFRS-1: Vorliegen einer Bedienungsanleitung* +
Test: Ausführen/Starten des Servers von einer projektfremden Person.

== Zusätzliche Anforderungen

=== Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
Unsere Anwendung besteht aus 2 Teilen, dem Frontend und dem Backend. 
Für das Entwickeln des Backends nutzen wir das SpringBoot Framework, da unser Team bereits einige Vorerfahrungen dazu hat und die Anbindung und Verwendung einer Datenbank damit einfach und flexibel ist.
Für das Frontend verwenden wir die ReactJS Bibliothek, da diese eine Vielzahl von schönen Nutzerelementen mit verschiedenen Animationen und Layouts bereitstellt.
        
Die Hardwareanforderungen unserer Anwendung orientieren sich an den Anforderungen des von uns verwendeten Frameworks. Für SpringBoot ist mindestens Java 8 vorausgesetzt, empfohlen wird aber Java 11, woraus sich folgende Hardwareanforderungen ergeben:
        
        2 GHz Prozessor (min 1,4 GHz x64)
        4 GB RAM
        7 GB freier Festplattenspeicher
        
        Wir empfehlen die Nutzung unserer Anwendung unter einem Linux Ubuntu Betriebssystem, da wir die Anwendung unter diesem entwickelt haben. Die Anwendung sollte aber auch auf jedem anderen System laufen, welches Java unterstützt.

=== Organisatorische Randbedingungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Das System muss von geschultem Personal gepflegt und gewartet werden.
* Neue User sollten mit der Software vor der ersten Nutzung vertraut gemacht werden.
* Die Software ist nur in englischer Sprache gehalten.

=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Die Lizensierung der Anwendungen wird vorausgesetzt.
* Die Einhaltung der DSGVO wird vorausgesetzt und ist vom Anwender zu prüfen.
* Der Urheberrechtsschutz muss vom Anwender gewährleistet werden.
