= Use-Case Model: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Allgemeine Informationen
// ...


== Identifizierte Use Cases
// Liste aller identifizierten Use Cases (priorisiert)
*für Akteur User:*
A* *UC01*: Ausleih
F* *UC02*: Rückgabe (eingabe ID -> Anzeige Lagerort)
A* *UC03*: Neu Aufnahme von Gegenständen (Leeres Fach finden)
A* *UC04*: Deinventarisierung (Entsorgung)
A* *UC05*: User Status ändern (Ausleih/Rückgabe)
A* *UC06*: Suchen von Objekten
A* *UC07*: Übersicht Anzeigen (User)
S* *UC08*: Übersicht Wartung (User/Reperatur Dienstleister)
S* *UC09*: System Rückmeldung bei Änderungen (an User)
S* *UC10*: Nutzungsverlauf (Gegenstände)
F* *UC11*: Nach Scannen ID (->Rückgabe)

*für Akteur Admin:* (nur User Verwaltung?)
S* *UC12*: Admin Anlegen User
S* *UC13*: Admin Bearbeiten User Rechte
S* *UC14*: Admin Bearbeiten User
F* *UC15*: Admin Löschen User
F* *UC16*: Backup Erstellung (Admin) Automatisch?

F* *UC17*: Authentifikation der Clients
F* *UC18*: Verschlüsselung der Kommunikation zwischen DB und WebAnwendung



== Use Case Diagramm
// ...

//Fügen Sie nachfolgend alle detailierten Use-Cases per Include ein.
//Dafür sollten Sie pro Use-Case eine Datei anlegen, die auf dem use_case_01.inc.adoc Template basiert.
<<<
include::use_case_01.inc.adoc[]
//<<<
//include::use_case_02.inc.adoc[]
//<<<
//include::use_case_03.inc.adoc[]
//<<<
//include::use_case_04.inc.adoc[]
//<<<
//include::use_case_05.inc.adoc[]
//<<<
//include::use_case_06.inc.adoc[]
//<<<
//include::use_case_07.inc.adoc[]
//<<<
//include::use_case_08.inc.adoc[]
//<<<
//include::use_case_09.inc.adoc[]
//<<<
//include::use_case_10.inc.adoc[]
